#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1617818168                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Ripple makes it easy and convenient to connect with people in your area.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Vladislav Kim                                
your_link                                 :                      
your_city                                 : New York                                
email_address                             : gazeromo@icloud.com
facebook_username                         :                                           
instagram_username                        : the3ripple
twitter_username                          : 
github_username                           : github.com/gazeromo
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Hyperlocal - Buy & Sell with Your Community
    description                           : Find unique products from local sellers near you.
    fontawesome_icon_name                 : store
    
  - title                                 : Community Market - Buy Local, Shop Smart
    description                           : Explore a world of unique products from your area.
    fontawesome_icon_name                 : magnifying-glass-dollar

  - title                                 : Connect and Communicate - Your Local Marketplace Chat
    description                           : Preview app video on the iPhone device simply by placing your video files in the videos folder.
    fontawesome_icon_name                 : comments-dollar

  - title                                 : Secure Transactions with QR Verification
    description                           : Confirm payments instantly and securely with QR codes
    fontawesome_icon_name                 : qrcode

  - title                                 : Get the Best Deals on Ripple
    description                           : Uncover Hidden Gems in Our Marketplace Listings.
    fontawesome_icon_name                 : badge-check
  
  - title                                 : Get a Clear Picture of Your Sales
    description                           : Keep Track of Your Sales and Optimize Your Business with Advanced Analytics.
    fontawesome_icon_name                 : chart-pie

  - title                                 : Discover Your Match - Effortless Listing Filtering at Its Best
    description                           : 
    fontawesome_icon_name                 : filter



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#6C63FF"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
